services:
  db:
    image: 'postgres:latest'
    container_name: '359_db'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

volumes:
  dbdata:
